stages:
  - deploy-poc

image: node:latest

deploy-poc:
  stage: deploy-poc
  tags:
    - docker-keo-runner
  script:
    - node -v
    - cp $ENV_DEVELOPMENT .env.production.local
    - npm install
    - CI='' npm run build
    - npm i -g firebase-tools@latest
    - firebase -P dev target:apply hosting dev_target mex-ocr-poc
    - firebase deploy -P dev --only hosting:dev_target --token $FIREBASE_TOKEN_DEV
  only:
    - main
    